### PR TITLE
Display a list of disks attached to a particular VM

### PR DESCRIPTION
**Pull request by swalberg**
cc/ @mheidenr

### CODE REVIEW

**Comment by mheidenr** [comment]
looks good, but I don't like the size formatting. Can we use a helper like https://rubygems.org/gems/filesize ?

**Comment by swalberg** [comment]
Awesome idea! Thanks.

**Comment by swalberg** [comment]
Done. I like this gem, thanks!

```
$ be knife vsphere vm disk list MYVM 
  0          Hard disk 1 143.24 GB
  1          Hard disk 2 143.25 GB```

**Comment by mheidenr** [comment]
very clean output :thumbsup:

**Pull request merged**
