### PR TITLE
vm network list initial upload

### PR DESCRIPTION
**Pull request by coda4096**
knife vsphere vm network list VMNAME

for a vm (VMNAME), list its network cards and for each network card, list its connected network (vlan)

currently not working.

I need some help with listing the networks that a NIC is connected to.

### CODE REVIEW

**Comment by coda4096** [comment]
Currently, this only lists the network cards on a VM. I need some help with listing a network cards' connected network. I think the code would be something like this?
<pre>
nic.network.each do |network|
   puts "#{ui.color('VLAN', :red)}: #{network.name}"
end
</pre>

**Comment by coda4096** [comment]
Also, when I use 
<pre>#{a.deviceInfo.summary}</pre>, I get an output like this <pre>DVSwitch: a8 8f 21 50 2e ac 27 e4-6a c1 84 0f 4d ac 1e b2</pre>.
How do you get the summary **text**

**Comment by coda4096** [comment]
Currently I am a bit closer, I can list the portgroupKey and switchUuid for each nic:
<pre>
    vm.config.hardware.device.each.grep(RbVmomi::VIM::VirtualEthernetCard).map do |nic|
      puts "#{ui.color('NIC', :cyan)}: #{nic.backing.port.portgroupKey}"
      puts "#{ui.color('NIC', :cyan)}: #{nic.backing.port.switchUuid}"
    end
</pre>

I need some help to be able to list the switchName or the DVPortgroup name please.

**Comment by coda4096** [comment]
ready

**Comment by swalberg** [comment]
Just used it and it works. Going to merge it, but I think there could be some future improvements to make it a bit faster. Right now it seems to loop through the DC networks once per NIC. So we could either cache that list or do an API call to do a lookup.

**Pull request merged**
