### PR TITLE
knife vsphere vm find --host_name

### PR DESCRIPTION
**Pull request by coda4096**
option :host_name,
         long: '--host_name',
         description: 'show name of the VMs host'

### CODE REVIEW

**Comment by coda4096** [comment]
ready

**Comment by swalberg** [comment]
Awesome thanks!

**Comment by coda4096** [comment]
Hi Sean, do you have an ETA for the next release version?

**Comment by swalberg** [comment]
Thanks for the reminder. Just pushed `1.2.25`

**Pull request merged**
