### PR TITLE
Clone to host

### PR DESCRIPTION
**Pull request by swalberg**
Fill out the relocation spec with a host so people can deploy to a specific host using `--host`.

Note that we're [required to select a pool](https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.RelocateSpec.html) in addition to the host because we're cloning. So we rely on the default pool picking logic.

### CODE REVIEW

**Comment by warroyo** [comment]
@swalberg I am running version `1.2.23` but this `--host` option does not seem to exist. Is this supposed to be working in that release?

**Comment by swalberg** [comment]
@warroyo Yup, seems to have been released with `1.2.22`. What kind of message are you getting, and what command are you running?

**Comment by warroyo** [comment]
I am not getting any errors, however it does not look like the parameter is being used. When i specify a host, it is not chosen.

**Comment by swalberg** [comment]
Could you run it with `-VV` and paste in the clone spec that gets sent to vmware?

PS I haven't forgotten about your other PR, it's a long weekend here and I didn't get any open source work done.

**Comment by warroyo** [comment]
Here is the piece of the clone spec that sets the host.

````
location: VirtualMachineRelocateSpec(
    datastore: Datastore("datastore-168909"),
    host: HostSystem("host-12398"),
    pool: ResourcePool("resgroup-6251")
  ),
````

I verified that `host-12398` matches the host I am providing in the `--host` option. So it does look like the option is being used. 

I removed the `--start` option, and now it is going to the correct host. It seems like when the Vm si starting up it relocates it.

**Pull request merged**
