### PR TITLE
Update vsphere_vm_clone.rb

### PR DESCRIPTION
**Pull request by petericebear**
Added --cram_reservation config and --ccorespersocket setting. 
#358 #353

### CODE REVIEW

**Comment by petericebear** [comment]
Sorry for the multiple commits, but with these changes you can change the corespersockets and set the memory reservation.

**Comment by swalberg** [comment]
I love it! Could I trouble you to add these new options to the README, please? I squash all the commits prior to merging so no worries there... Thanks!

**Comment by petericebear** [comment]
Yeah, sure thing. Will do this later today.

**Comment by petericebear** [comment]
Can you check? :)

**Comment by swalberg** [comment]
Good stuff! Thanks for the contribution. I'll cut a release later today as I still haven't had my ☕️ yet :)

**Pull request merged**
