### PR TITLE
vsphere vm network list VMNAME

### PR DESCRIPTION
**Pull request by coda4096**
list networks for a VM

### CODE REVIEW

**Comment by coda4096** [comment]
may need some help isolating just the vsphere_vm_network_list.rb file

**Comment by swalberg** [comment]
Hi, I'm about to turn in for the night, but it looks like you're pushing some unrelated changes because your local repo is behind the project's repo.

**Comment by swalberg** [comment]
Hi, for some reason I missed your comment there when I posted mine. Let me know if you need a hand.

**Comment by coda4096** [comment]
Hi Sean
Yes, I need a hand with committing to a new branch for "vm nic delete" and then doing a pull request.
Thank you

**Comment by swalberg** [comment]
First make a backup copy of your new file in case I'm wrong ;)

Try adding the upstream repo as a new remote:

```
git remote add upstream git@github.com:chef-partners/knife-vsphere.git
```

pull in changes

```
git fetch upstream # can't remember if you need "master" after that
```

reset your master to match upstream

```
git reset upstream/master # your local master is the same as the project's
git push -f origin master # force push to make your fork on GH the same
```

Now create a branch for your work

```
git checkout -b network_list
```

I think your change should be there. Check it out with 

```
git status
```

It should show no changes, and just the one addition.

Then, check in the file and push it to GitHub:

```
git add lib/chef/knife/vsphere_vm_network_list.rb
git commit # Give it a commit message after
git push origin network_list
```

Make the PR. 

Then, in the future:

```
git checkout master # switch to your local master
git pull upstream master # grab changes from the project
git push origin master # may as well keep your fork up to date
```

And after that, for more work, create a branch, push it to origin, pull request.

**Comment by swalberg** [comment]
Meant to add -- try to avoid committing code to master as that means your master branch diverges from the projects, which then means your commits include a lot of extra stuff. Always commit to a branch and keep your master up to date with upstream, and things will go a lot better.

**Comment by coda4096** [comment]
Thanks a lot for your help. I am having trouble with the fetch upstream command, i get this error:
<pre>
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
</pre>
Does the add upstream command need my username?

**Comment by coda4096** [comment]
I have backup up my files, so I dont mind if we clear my repo and "start again"

**Comment by swalberg** [comment]
Yup, that works. Delete your local repo, delete your fork on GitHub, refork the repo and clone, then start at `git checkout -b network_list`.

**Pull request closed without merging**
