### PR TITLE
New function to change network on VM

### PR DESCRIPTION
**Pull request by omgroves**
This was briefly discussed in #249 . Takes a network name and changes NICs on the VM to that network.

### CODE REVIEW

**Comment by swalberg** [comment]
Hi, thanks for the PR! I will try it out soon.

What's the use-case for changing all nics on a vm to the same network rather than a single nic? I'm thinking of when you have a VM with a front facing NIC, and one to a storage system or database on a different network. Do you bond all the interfaces?

Could you also please add something to the README, otherwise no one will be able to find this!

Thanks,

Sean

**Comment by omgroves** [comment]
That's a good call Sean, I agree this probably makes more sense a single NIC at a time. I've altered this to only change the first NIC. Definitely open to other suggestions if another use-case seems more prevalent.

Also added entry to the README.

-Owen

**Comment by swalberg** [comment]
What would you think about making that `0` a command line option with a default value of `0` so that our users can pick if they wanted a different nic other than the first? 

Have a look at [this](https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_clone.rb#L309-L312) for a code example of how to set up the option, and [this](https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_clone.rb#L936) for how you get the value.

**Comment by omgroves** [comment]
Great suggestion, much appreciated! I have added this option, tested, and updated the README.

-Owen

**Comment by swalberg** [comment]
Haven't forgotten about this. Should be able to test it out later today.

**Comment by swalberg** [comment]
Tested this out on the VDS case and it works great. Sorry for the delay -- merging this now and will cut a release! Thanks a million for the improvement.

**Pull request merged**
